/*
 * colors.cpp
 *
 *  Created on: 28.10.2021
 *      Author: Laptop
 */
#include "colors.h"



const uint16_t ColorTab[] = {

		CO_COLOR_358_RED,
		CO_COLOR_359_RED,
		CO_COLOR_360_RED,
		CO_COLOR_0_RED,
		CO_COLOR_1_RED,
		CO_COLOR_2_RED,
		CO_COLOR_3_RED,
		CO_COLOR_4_RED,

		CO_COLOR_5_ORANGE,
		CO_COLOR_7_ORANGE,
		CO_COLOR_8_ORANGE,
		CO_COLOR_10_ORANGE,

		CO_COLOR_15_YELLOW,
		CO_COLOR_20_YELLOW,
		CO_COLOR_23_YELLOW,
		CO_COLOR_25_YELLOW,
		CO_COLOR_30_YELLOW,
		CO_COLOR_33_YELLOW,
		CO_COLOR_35_YELLOW_GR,
		CO_COLOR_40_YELLO_GR,

		CO_COLOR_50_GREEN,
		CO_COLOR_60_GREEN,
		CO_COLOR_70_GREEN,
		CO_COLOR_80_GREEN,
		CO_COLOR_90_GREEN,
		CO_COLOR_100_GREEN,
		CO_COLOR_110_GREEN,
		CO_COLOR_120_GREEN,
		CO_COLOR_124_GREEN_BL,			  //!!

		CO_COLOR_130_BLUE_GR,
		CO_COLOR_140_BLUE_BRIGHT,
		CO_COLOR_160_BLUE_BRIGHT,
		CO_COLOR_180_BLUE,
		CO_COLOR_200_BLUE,
		CO_COLOR_210_BLUE,
		CO_COLOR_230_BLUE,
		CO_COLOR_240_BLUE_STRONG,
		CO_COLOR_250_BLUE_PURPL,

		CO_COLOR_260_PURPL_BLUE,
		CO_COLOR_270_PURPLE_BRIGHT,
		CO_COLOR_280_PURPLE,
		CO_COLOR_290_PURPLE,
		CO_COLOR_300_PURPLE,
		CO_COLOR_300_PURPLE,
		CO_COLOR_310_PURPLE,
		CO_COLOR_320_PURPLE,
		CO_COLOR_330_PURPLE,
		CO_COLOR_340_PURPLE_STRONG,

		CO_COLOR_350_PINK
};



const struct def_color_srt ColorStructStandard = {

		&ColorTab[0],
		sizeof(ColorTab)/sizeof(uint16_t)

};


const uint16_t ColorTabDark[] = {

/*
		CO_COLOR_50_GREEN,
		CO_COLOR_60_GREEN,
		CO_COLOR_70_GREEN,
		CO_COLOR_80_GREEN,
		CO_COLOR_90_GREEN,
*/
		CO_COLOR_100_GREEN,
		CO_COLOR_110_GREEN,
		CO_COLOR_120_GREEN,
		CO_COLOR_124_GREEN_BL,			  //!!

		CO_COLOR_130_BLUE_GR,
		CO_COLOR_140_BLUE_BRIGHT,
		CO_COLOR_160_BLUE_BRIGHT,
		CO_COLOR_180_BLUE,
		CO_COLOR_200_BLUE,
		CO_COLOR_210_BLUE,
		CO_COLOR_230_BLUE,
		CO_COLOR_240_BLUE_STRONG,
		CO_COLOR_250_BLUE_PURPL,

		CO_COLOR_260_PURPL_BLUE,
		CO_COLOR_270_PURPLE_BRIGHT,
		CO_COLOR_280_PURPLE,
		CO_COLOR_290_PURPLE,
		CO_COLOR_300_PURPLE,
		CO_COLOR_300_PURPLE,
		CO_COLOR_310_PURPLE,
		CO_COLOR_320_PURPLE,
		CO_COLOR_330_PURPLE,
		CO_COLOR_340_PURPLE_STRONG,
//		CO_COLOR_350_PINK
};


const struct def_color_srt ColorStructDark = {

		&ColorTabDark[0],
		sizeof(ColorTabDark)/sizeof(uint16_t)

};


uint16_t funGetSizeofColorTab()
{
	return sizeof(ColorTab)/sizeof(uint16_t);
}








